M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu20.04.1} date Sun 23 Apr 2023 02:30:32 PM WIB
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-04-23T14:30:32+07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
%
G90
G05
T1
X5.3254Y-2.1483
X5.4986Y-2.1483
T0
M30
